### ISSUE TITLE
Error: Application crashes when no admin permission granted.

### ISSUE THREAD

**Issue by nuriofernandez** [bennyborn/ClickNLoadDecrypt#1]
The application crashes in case you start it without admin permissions.
```
this.Listener = new HttpListener();
this.Listener.Prefixes.Add("http://*:9666/");
this.Listener.Start();
```
```
System.Net.HttpListenerException: 'Access is denied'
This exception was originally thrown at this call stack:
    [External Code]
    ClickNLoadDecrypt.MainWindow.Window_Loaded(object, System.Windows.RoutedEventArgs) in MainWindow.xaml.cs
    [External Code]
```

More info:
https://stackoverflow.com/a/4115328/7343009
https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/configuring-http-and-https?redirectedfrom=MSDN

**Comment by bennyborn** [comment]
Hi there, thanks for the information but this project was only meant for me as a personal practice while looking into C#. It is now about 8 years old and I haven't touched C# ever since.

So while I invite you to provide a PR, that I'd be happy to merge, there is little to no chance for me picking up on this project in the next years ;)

**Comment by bennyborn** [comment]
Thanks to you @xXNurioXx I had to give it a try to get a build running and noticed I'd already done some "improvements" in a devel-branch which were not merged until today. So feel free to grab the most recent commit.
